site_name: Lean4url Documentation
site_description: Lean4url 文档
site_author: Rex Wang
site_url: https://lean4url.readthedocs.io/

repo_name: RexWzh/Lean4url
repo_url: https://github.com/RexWzh/Lean4url
edit_uri: edit/main/docs/

docs_dir: docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.prune
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
  language: en

plugins:
  - search
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "Lean4url Documentation (en)"
        - locale: zh
          name: 中文
          build: true
          site_name: "Lean4url 文档 (zh)"
          nav_translations:
            Home: 首页
            Getting Started: 开始使用
            Quick Start: 快速开始

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: 中文
      link: /zh/
      lang: zh
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/
nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quickstart.md